source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def common
    pod 'Alamofire', '4.9.1'
    pod 'RxSwift', '5.1.1'
    pod 'RxCocoa', '5.1.1'
end

target 'RxAlamofire-iOS-Example' do
    #platform :ios, '11.0'
    common
end

target 'RxAlamofire-tvOS-Example' do
    #platform :tvos, '9.0'
    common
end

target 'RxAlamofire-iOS' do
   common
end

target 'RxAlamofireTests' do
    common
    pod 'OHHTTPStubs', '~> 5.0'
    pod 'OHHTTPStubs/Swift', '~> 5.0'
    pod 'RxBlocking', '5.1.1'
end

target 'RxAlamofire-tvOS' do
    common
end
